eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: szhaos-feign
  zipkin:
    base-url: http://127.0.0.1:9411

feign:
  hystrix:
    enabled: true